// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvNW1ZQxhSBrk0f0ALEW3sU5fizJyIjM',
    appId: '1:836111214737:web:44effb2afb3228ccbbb730',
    messagingSenderId: '836111214737',
    projectId: 'tasks-921f6',
    authDomain: 'tasks-921f6.firebaseapp.com',
    storageBucket: 'tasks-921f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUQVuD0aUrwgG1rbaI4uu2flvS3ahanXA',
    appId: '1:836111214737:android:961fb2a471e50652bbb730',
    messagingSenderId: '836111214737',
    projectId: 'tasks-921f6',
    storageBucket: 'tasks-921f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7EOpq-PDrFUuIVfqq-EX3uJnigFlM-PM',
    appId: '1:836111214737:ios:f3ff89ffcd22e450bbb730',
    messagingSenderId: '836111214737',
    projectId: 'tasks-921f6',
    storageBucket: 'tasks-921f6.appspot.com',
    iosBundleId: 'com.example.aplikacija',
  );
}
